name: Jira Integration

on:
  issues:
    types: [opened, closed]

jobs:
  jira-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Jira Issue
        if: github.event.action == 'opened'
        uses: atlassian/gajira-create-issue@v3
        with:
          issueType: '10001' # Story
          projectKey: 'DASOMFE'
          summary: ${{ github.event.issue.title }}
          description: |
            GitHub Issue: ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}
          fields: |
            {
              "customfield_10014": "${{ github.event.issue.number }}"
            }
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Close Jira Issue
        if: github.event.action == 'closed'
        uses: atlassian/gajira-transition-issue@v3
        with:
          issueKey: DASOMFE-${{ github.event.issue.number }}
          transition: 'Done'
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
